### ISSUE TITLE
Bluetooth sleep/disconnect

### ISSUE THREAD

**Issue by d01** [daniel5151/surface-dial-linux#3]
So this is the obvious one; this device likes to sleep after a timeout, and takes ~2000-5000ms to reconnect once you start interacting with it. 

Do you observe the same thing? If so, have you been able to do anything - lengthen the timeout, or otherwise speed it back up? I'm guessing(/hoping?) that Microsoft themselves found some way not to have a 5 second wait time after device wake up.

**Comment by daniel5151** [comment]
Yep, I get the same thing, even on Windows.

Given that the Surface Dial is aimed towards more "creative" use-cases (as opposed to the occasional scroll / volume control), I guess it makes sense to live with the short timeout + long reconnect since it greatly stretches out the battery life. This is pure conjecture of course.

I haven't tested this, but it _might_ be possible extend the timeout by sending "heartbeat" messages to the Dial (e.g: cycling the haptics mode), but it's not something I've personally experimented with.

**Comment by d01** [comment]
Yeah, sure enough, once I knew what to look for, the internet has a trail of misery related to this:

- https://answers.microsoft.com/en-us/surface/forum/surfaccesso-surfweel/surface-dial-sleep-mode-a-big-issue/5c839b74-fa63-4fad-b112-29bc38e6802b
- https://stackoverflow.com/questions/44322604/turning-off-microsoft-surface-dial-sleep-mode
- https://www.xspdf.com/questions/39500.shtml
- https://www.reddit.com/r/Surface/comments/8at1yg/how_do_you_keep_surface_dial_on_at_all_time/
- https://savethehuman5.com/forum/troubleshooting/surface-dial-standby-mode/

Your idea about trying to cycle the haptics mode is very clever. I tried it, by making a timeout on recv in all cases and using that to drive a heartbeat. It didn't work. 

It wouldn't seem right to keep this issue open, since it's not an issue with anything you've written. 

Bummer. Microsoft strikes again. A flick of someone's finger in Redmond, and this device would have made a whole lot of people a whole lot less unhappy. But Microsoft, and most all the closed source shops, not being willing to lift a finger, is a very old story.

**Comment by daniel5151** [comment]
So, I'm actually working at Microsoft right now (not in the Surface division), which mean that I could get in touch with one of the firmware engineers who worked on the Surface Dial. I asked him if there's any way to extend the disconnect timeout, but alas, it turns out that the timeout can only be reset through physical interaction. Oof.

Yeah... while Microsoft has certainly been getting better at Open Source lately (case in point, my day-job is entirely open-source), I don't think that culture has made its way into the hardware divisions just yet. Maybe one day...

**Comment by d01** [comment]
Haha. That's amazing. Well, there's something comfortable about at least knowing for sure, even when the news is bad. 

Goes to show how hard it is to ship product. You can get 100,000 things right, and 1 mistake can doom you. 

Open source was just so obviously destined to be a winning philosophy. Case in point, if they had their firmware on github, the problem would be fixed years ago, 50/50 MSFT even takes the patch at that point, and either way they'd probably have sold 2-4x units. Instead I ended up returning mine back to Amazon, which is just really sad. It's a great little piece of hardware, with just that one fatal flaw.
