### ISSUE TITLE
Crash on longpress & when installing daemon on Ubuntu

### ISSUE THREAD

**Issue by alexandrunastase** [daniel5151/surface-dial-linux#9]
**Describe the bug**

_A clear and concise description of what the bug is._

**Desktop (please complete the following information):**
- Distro: 21.10
- Desktop Environment: Gnome
- output of `uname -a`: 
Linux zen 5.13.0-35-generic #40-Ubuntu SMP Mon Mar 7 08:03:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
**Service Logs**

_Please copy the output of `journalctl -u surface-dial.service` / the daemon's `stdout/stderr`._
```
long press!
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/controller/controls/media_with_volume.rs:17:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Notification error: "The name org.freedesktop.Notifications was not provided by any .service files"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Dbus(D-Bus error: The name org.freedesktop.Notifications was not provided by any .service files (org.freedesktop.DBus.Error.ServiceUnknown)) }', src/main.rs:67:14

```
When possible, please reproduce the bug with the `RUST_BACKTRACE=1` environment variable set. Having a detailed backtrace will make it easier to diagnose (and hopefully fix) the bug.

When I run directly scrolling works but fails when I long press I get an error. I followed the instructions in the readme but maybe you are using another system and I have something missing on my Ubuntu.

When I tried installing the daemon it also failed, but the scrolling was also not working. There was no output in the journalctl so I this is the output.

![image](https://user-images.githubusercontent.com/2458807/158325095-ee595032-6510-4118-aaf5-c07f90531768.png)

Also in text format:
```
 mar 15 08:04:57 zen surface-dial-daemon[24127]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDe>
mar 15 08:04:57 zen surface-dial-daemon[24127]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
mar 15 08:04:57 zen surface-dial-daemon[24127]: thread '<unnamed>' panicked at 'Could not recv event', src/dial_device/mod.rs:135:24
mar 15 08:04:57 zen surface-dial-daemon[24127]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/dial_device/hapti>
mar 15 08:04:57 zen surface-dial-daemon[24127]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/controller/contro>
```

The daemon seems like a permission issue but I'm not super advanced with systemd & co so I tried rerunning the installation commands from the readme, but it still didn't fix it.

**Comment by daniel5151** [comment]
As you've correctly identified, it looks like you've got some permission / setup / dependency issues on your machine.

- The reason it crashes on longpress is because that's the first time `surface-dial-linux` tries to contact the notification service on your machine (to display the "menu"). I'm not entirely sure why it's failing here (unless Ubuntu 21.10 changed how notifications are handled?), but in any case, if you google that error string under `Error: Notification error: `, it seems there are some things you can try.
    - Alternatively, as mentioned in the readme, `surface-dial-linux` will NOT work when running as the root user (or any user that isn't the currently running user, for that matter). Hence why it needs to be set up as a systemd _user_ service, rather than as a system service (i.e: so it can access the user session's d-bus)
- As for the systemd setup... that I'm not too sure about. See if you can get things at least somewhat working using those `chmod` hacks I mentioned in the README, while running the daemon directly from your own user terminal. At least then you'll be able to determine which files specifically have permission issues.

I'm not sure how much more help I'll be able to provide aside from those bits of advice, as I have neither a Ubuntu 21.10 installation, nor a Surface Dial (due to an unfortunate mishap during shipping 😢), and it seems to me that there isn't anything wrong with the code of `surface-dial-linux` itself.

**Comment by alexandrunastase** [comment]
It's actually quite strange. I tried again now and none of the issues happen anymore. Maybe it is something that can happen the first time you install it or maybe there is something wrong with my Ubuntu, but in any case the restart seemed to have fixed the issue. 
Thanks for building and publishing this btw :+1:
